#include "Attribute.h"

#include "strings.h"

const int Attribute::AttributeNames[] = {
    IDS_ATTRIBUTE_NAME_GENERIC_MAXHEALTH,
    IDS_ATTRIBUTE_NAME_GENERIC_FOLLOWRANGE,
    IDS_ATTRIBUTE_NAME_GENERIC_KNOCKBACKRESISTANCE,
    IDS_ATTRIBUTE_NAME_GENERIC_MOVEMENTSPEED,
    IDS_ATTRIBUTE_NAME_GENERIC_ATTACKDAMAGE,
    IDS_ATTRIBUTE_NAME_HORSE_JUMPSTRENGTH,
    IDS_ATTRIBUTE_NAME_ZOMBIE_SPAWNREINFORCEMENTS,
};

int Attribute::yuri_5578(eATTRIBUTE_ID yuri_6674) { return AttributeNames[yuri_6674]; }