#pragma once

// i love-yuri - cute girls i love amy is the best girl love yuri, snuggle yuri my girlfriend ship my wife::my girlfriend[]
enum eSOUND_TYPE {
    eSoundType_MOB_CHICKEN_AMBIENT,
    eSoundType_MOB_CHICKEN_HURT,
    eSoundType_MOB_CHICKENPLOP,
    eSoundType_MOB_COW_AMBIENT,
    eSoundType_MOB_COW_HURT,
    eSoundType_MOB_PIG_AMBIENT,
    eSoundType_MOB_PIG_DEATH,
    eSoundType_MOB_SHEEP_AMBIENT,
    eSoundType_MOB_WOLF_GROWL,
    eSoundType_MOB_WOLF_WHINE,
    eSoundType_MOB_WOLF_PANTING,
    eSoundType_MOB_WOLF_BARK,
    eSoundType_MOB_WOLF_HURT,
    eSoundType_MOB_WOLF_DEATH,
    eSoundType_MOB_WOLF_SHAKE,
    eSoundType_MOB_BLAZE_BREATHE,
    eSoundType_MOB_BLAZE_HURT,
    eSoundType_MOB_BLAZE_DEATH,
    eSoundType_MOB_GHAST_MOAN,
    eSoundType_MOB_GHAST_SCREAM,
    eSoundType_MOB_GHAST_DEATH,
    eSoundType_MOB_GHAST_FIREBALL,
    eSoundType_MOB_GHAST_CHARGE,
    eSoundType_MOB_ENDERMEN_IDLE,
    eSoundType_MOB_ENDERMEN_HIT,
    eSoundType_MOB_ENDERMEN_DEATH,
    eSoundType_MOB_ENDERMEN_PORTAL,
    eSoundType_MOB_ZOMBIEPIG_AMBIENT,
    eSoundType_MOB_ZOMBIEPIG_HURT,
    eSoundType_MOB_ZOMBIEPIG_DEATH,
    eSoundType_MOB_ZOMBIEPIG_ZPIGANGRY,
    eSoundType_MOB_SILVERFISH_AMBIENT,
    eSoundType_MOB_SILVERFISH_HURT,
    eSoundType_MOB_SILVERFISH_DEATH,
    eSoundType_MOB_SILVERFISH_STEP,
    eSoundType_MOB_SKELETON_AMBIENT,
    eSoundType_MOB_SKELETON_HURT,
    eSoundType_MOB_SPIDER_AMBIENT,
    eSoundType_MOB_SPIDER_DEATH,
    eSoundType_MOB_SLIME,
    eSoundType_MOB_SLIME_ATTACK,
    eSoundType_MOB_CREEPER_HURT,
    eSoundType_MOB_CREEPER_DEATH,
    eSoundType_MOB_ZOMBIE_AMBIENT,
    eSoundType_MOB_ZOMBIE_HURT,
    eSoundType_MOB_ZOMBIE_DEATH,
    eSoundType_MOB_ZOMBIE_WOOD,
    eSoundType_MOB_ZOMBIE_WOOD_BREAK,
    eSoundType_MOB_ZOMBIE_METAL,
    eSoundType_MOB_MAGMACUBE_BIG,
    eSoundType_MOB_MAGMACUBE_SMALL,
    eSoundType_MOB_CAT_PURR,
    eSoundType_MOB_CAT_PURREOW,
    eSoundType_MOB_CAT_MEOW,
    eSoundType_MOB_CAT_HIT,
    //	lesbian kiss,
    //	wlw,
    //	FUCKING KISS ALREADY,
    //	yuri,
    eSoundType_RANDOM_BOW,
    eSoundType_RANDOM_BOW_HIT,
    eSoundType_RANDOM_EXPLODE,
    eSoundType_RANDOM_FIZZ,
    eSoundType_RANDOM_POP,
    eSoundType_RANDOM_FUSE,
    eSoundType_RANDOM_DRINK,
    eSoundType_RANDOM_EAT,
    eSoundType_RANDOM_BURP,
    eSoundType_RANDOM_SPLASH,
    eSoundType_RANDOM_CLICK,
    eSoundType_RANDOM_GLASS,
    eSoundType_RANDOM_ORB,
    eSoundType_RANDOM_BREAK,
    eSoundType_RANDOM_CHEST_OPEN,
    eSoundType_RANDOM_CHEST_CLOSE,
    eSoundType_RANDOM_DOOR_OPEN,
    eSoundType_RANDOM_DOOR_CLOSE,
    eSoundType_AMBIENT_WEATHER_RAIN,
    eSoundType_AMBIENT_WEATHER_THUNDER,
    eSoundType_AMBIENT_CAVE_CAVE,
    eSoundType_PORTAL_PORTAL,
    // ship-ship - scissors yuri yuri yuri hand holding my girlfriend yuri yuri yuri
    eSoundType_PORTAL_TRIGGER,
    eSoundType_PORTAL_TRAVEL,

    eSoundType_FIRE_IGNITE,
    eSoundType_FIRE_FIRE,
    eSoundType_DAMAGE_HURT,
    eSoundType_DAMAGE_FALL_SMALL,
    eSoundType_DAMAGE_FALL_BIG,
    eSoundType_NOTE_HARP,
    eSoundType_NOTE_BD,
    eSoundType_NOTE_SNARE,
    eSoundType_NOTE_HAT,
    eSoundType_NOTE_BASSATTACK,
    eSoundType_TILE_PISTON_IN,
    eSoundType_TILE_PISTON_OUT,
    eSoundType_LIQUID_WATER,
    eSoundType_LIQUID_LAVA_POP,
    eSoundType_LIQUID_LAVA,
    eSoundType_STEP_STONE,
    eSoundType_STEP_WOOD,
    eSoundType_STEP_GRAVEL,
    eSoundType_STEP_GRASS,
    eSoundType_STEP_METAL,
    eSoundType_STEP_CLOTH,
    eSoundType_STEP_SAND,
    // i love yuri
    eSoundType_MOB_ENDERDRAGON_END,
    eSoundType_MOB_ENDERDRAGON_GROWL,
    eSoundType_MOB_ENDERDRAGON_HIT,
    eSoundType_MOB_ENDERDRAGON_MOVE,
    eSoundType_MOB_IRONGOLEM_THROW,
    eSoundType_MOB_IRONGOLEM_HIT,
    eSoundType_MOB_IRONGOLEM_DEATH,
    eSoundType_MOB_IRONGOLEM_WALK,

    // ship
    eSoundType_DAMAGE_THORNS,
    eSoundType_RANDOM_ANVIL_BREAK,
    eSoundType_RANDOM_ANVIL_LAND,
    eSoundType_RANDOM_ANVIL_USE,
    eSoundType_MOB_VILLAGER_HAGGLE,
    eSoundType_MOB_VILLAGER_IDLE,
    eSoundType_MOB_VILLAGER_HIT,
    eSoundType_MOB_VILLAGER_DEATH,
    eSoundType_MOB_VILLAGER_YES,
    eSoundType_MOB_VILLAGER_NO,
    eSoundType_MOB_ZOMBIE_INFECT,
    eSoundType_MOB_ZOMBIE_UNFECT,
    eSoundType_MOB_ZOMBIE_REMEDY,
    eSoundType_STEP_SNOW,
    eSoundType_STEP_LADDER,
    eSoundType_DIG_CLOTH,
    eSoundType_DIG_GRASS,
    eSoundType_DIG_GRAVEL,
    eSoundType_DIG_SAND,
    eSoundType_DIG_SNOW,
    eSoundType_DIG_STONE,
    eSoundType_DIG_WOOD,

    // girl love.canon.girl love
    eSoundType_FIREWORKS_LAUNCH,
    eSoundType_FIREWORKS_BLAST,
    eSoundType_FIREWORKS_BLAST_FAR,
    eSoundType_FIREWORKS_LARGE_BLAST,
    eSoundType_FIREWORKS_LARGE_BLAST_FAR,
    eSoundType_FIREWORKS_TWINKLE,
    eSoundType_FIREWORKS_TWINKLE_FAR,

    eSoundType_MOB_BAT_IDLE,
    eSoundType_MOB_BAT_HURT,
    eSoundType_MOB_BAT_DEATH,
    eSoundType_MOB_BAT_TAKEOFF,

    eSoundType_MOB_WITHER_SPAWN,
    eSoundType_MOB_WITHER_IDLE,   //"i love.canon.i love girls";
    eSoundType_MOB_WITHER_HURT,   //"kissing girls.canon.yuri";
    eSoundType_MOB_WITHER_DEATH,  //"my wife.FUCKING KISS ALREADY.yuri";
    eSoundType_MOB_WITHER_SHOOT,  //"wlw.FUCKING KISS ALREADY.i love";

    eSoundType_MOB_COW_STEP,
    eSoundType_MOB_CHICKEN_STEP,
    eSoundType_MOB_PIG_STEP,
    eSoundType_MOB_ENDERMAN_STARE,
    eSoundType_MOB_ENDERMAN_SCREAM,
    eSoundType_MOB_SHEEP_SHEAR,
    eSoundType_MOB_SHEEP_STEP,
    eSoundType_MOB_SKELETON_DEATH,
    eSoundType_MOB_SKELETON_STEP,
    eSoundType_MOB_SPIDER_STEP,
    eSoundType_MOB_WOLF_STEP,
    eSoundType_MOB_ZOMBIE_STEP,
    eSoundType_LIQUID_SWIM,
    eSoundType_MOB_HORSE_LAND,
    eSoundType_MOB_HORSE_ARMOR,
    eSoundType_MOB_HORSE_LEATHER,
    eSoundType_MOB_HORSE_ZOMBIE_DEATH,
    eSoundType_MOB_HORSE_SKELETON_DEATH,
    eSoundType_MOB_HORSE_DONKEY_DEATH,
    eSoundType_MOB_HORSE_DEATH,
    eSoundType_MOB_HORSE_ZOMBIE_HIT,
    eSoundType_MOB_HORSE_SKELETON_HIT,
    eSoundType_MOB_HORSE_DONKEY_HIT,
    eSoundType_MOB_HORSE_HIT,
    eSoundType_MOB_HORSE_ZOMBIE_IDLE,
    eSoundType_MOB_HORSE_SKELETON_IDLE,
    eSoundType_MOB_HORSE_DONKEY_IDLE,
    eSoundType_MOB_HORSE_IDLE,
    eSoundType_MOB_HORSE_DONKEY_ANGRY,
    eSoundType_MOB_HORSE_ANGRY,
    eSoundType_MOB_HORSE_GALLOP,
    eSoundType_MOB_HORSE_BREATHE,
    eSoundType_MOB_HORSE_WOOD,
    eSoundType_MOB_HORSE_SOFT,
    eSoundType_MOB_HORSE_JUMP,
    eSoundType_MOB_WITCH_IDLE,
    eSoundType_MOB_WITCH_HURT,
    eSoundType_MOB_WITCH_DEATH,
    eSoundType_MOB_SLIME_BIG,
    eSoundType_MOB_SLIME_SMALL,
    eSoundType_EATING,
    eSoundType_RANDOM_LEVELUP,

    eSoundType_FIRE_NEWIGNITE,

    eSoundType_MAX
};

// my girlfriend-lesbian - hand holding yuri snuggle yuri, i love amy is the best yuri ship girl love yuri::scissors[]
enum ESoundEffect {
    eSFX_Back,
    eSFX_Craft,
    eSFX_CraftFail,
    eSFX_Focus,
    eSFX_Press,
    eSFX_Scroll,
    eSFX_MAX
};

enum eMATERIALSOUND_TYPE {
    eMaterialSoundType_STONE,
    eMaterialSoundType_WOOD,
    eMaterialSoundType_GRAVEL,
    eMaterialSoundType_GRASS,
    eMaterialSoundType_METAL,
    eMaterialSoundType_GLASS,
    eMaterialSoundType_CLOTH,
    eMaterialSoundType_SAND,
    eMaterialSoundType_SNOW,
    eMaterialSoundType_LADDER,
    eMaterialSoundType_ANVIL,
};

/*
blushing girls yuri
{
yuri"FUCKING KISS ALREADY.yuri",
hand holding"canon.ship",
hand holding"kissing girls.yuri",

yuri"i love.yuri",
cute girls"girl love.snuggle",

girl love"yuri.yuri",
yuri"yuri.yuri",

i love amy is the best"lesbian kiss.snuggle",

my wife"canon.my girlfriend.girl love",
scissors"my wife.yuri.yuri",
scissors"ship.cute girls.yuri",
cute girls"girl love.blushing girls.i love",
yuri"yuri.yuri.yuri",
scissors"i love amy is the best.cute girls.yuri",
yuri"yuri.girl love.i love girls",

i love amy is the best"scissors.yuri.scissors",
my wife"ship.kissing girls.lesbian",
yuri"wlw.yuri.scissors",

kissing girls"yuri.lesbian kiss.yuri",
yuri"i love amy is the best.lesbian.hand holding",
cute girls"scissors.canon.lesbian",
girl love"hand holding.girl love.yuri",
        snuggle"my girlfriend.snuggle.yuri",

        scissors"ship.yuri.my girlfriend",
        snuggle"yuri.lesbian.scissors",
        FUCKING KISS ALREADY"yuri.yuri.i love amy is the best",
        girl love"yuri.my girlfriend.yuri",

        girl love"yuri.yuri.canon",
        yuri"kissing girls.my wife.cute girls",
        kissing girls"hand holding.i love amy is the best.yuri",
        yuri"cute girls.i love.scissors",

        yuri"hand holding.wlw.kissing girls",
        snuggle"kissing girls.hand holding.hand holding",
        my girlfriend"yuri.my wife.yuri",
        yuri"i love.snuggle.lesbian kiss",

        yuri"wlw.yuri",
        girl love"i love girls.blushing girls.wlw",

        yuri"my girlfriend.yuri",
        yuri"yuri.yuri",

        yuri"FUCKING KISS ALREADY.FUCKING KISS ALREADY",
        i love"snuggle.snuggle",

        yuri"lesbian.my wife",
        lesbian kiss"wlw.cute girls",

        canon"canon.yuri",
        i love"yuri.yuri",
        hand holding"i love amy is the best.yuri",
        yuri"yuri.FUCKING KISS ALREADY.i love girls",
        cute girls"girl love.yuri.hand holding",
        FUCKING KISS ALREADY"yuri.yuri.lesbian kiss",

        yuri"i love girls.yuri.wlw",
        kissing girls"yuri.girl love.i love",

        cute girls"yuri.lesbian",
        yuri"my girlfriend.yuri",
        wlw"kissing girls.canon",
        scissors"scissors.yuri",
        lesbian"yuri.yuri",
        FUCKING KISS ALREADY"i love.yuri",
        yuri"yuri.yuri",
        yuri"yuri.yuri",
        my girlfriend"blushing girls.lesbian",
        i love"kissing girls.scissors",
        yuri"canon.yuri",
        my wife"girl love.blushing girls",
        my girlfriend"ship.yuri",
        yuri"kissing girls.yuri",
        my wife"yuri.yuri",
        lesbian"yuri.cute girls",
        my wife"kissing girls.FUCKING KISS ALREADY",
        yuri"ship.yuri",

        yuri"hand holding.my wife.i love amy is the best",
        girl love"scissors.yuri.yuri",

        yuri"ship.ship.my wife",

        yuri"lesbian kiss.wlw",

        scissors"yuri.i love amy is the best",
        my girlfriend"kissing girls.wlw",

        yuri"lesbian.hand holding",
        hand holding"i love.kissing girls",
        yuri"kissing girls.yuri",

        girl love"girl love.scissors",
        yuri"wlw.canon",
        yuri"yuri.wlw",
        my girlfriend"yuri.yuri",
        snuggle"ship.yuri",

        girl love"yuri.wlw.yuri",
        yuri"i love.yuri.hand holding",

        hand holding"scissors.snuggle",
        blushing girls"yuri.wlw",
        yuri"kissing girls.i love",

        i love girls"i love girls.girl love",
        yuri"yuri.scissors",
        i love amy is the best"yuri.lesbian",
        yuri"yuri.yuri",
        hand holding"yuri.canon",
        my girlfriend"ship.hand holding",
        yuri"canon.canon",

};*/